### ISSUE TITLE
Usage whith templating engine ?

### ISSUE THREAD

**Issue by jimblue** [awmottaz/prettier-plugin-void-html#15]
Hello,

First thank you for this amazing plugin. 🙏🏼 

I'm trying to use it with antlers and twig files, but I'm getting weird results.

For exemple the following HTML:

```html
<link rel="manifest" href="/manifest.webmanifest" />
{{ vite src="resources/scss/main.scss" }}
```

is formated:
```html
<link rel="manifest" href="/manifest.webmanifest" />
<aex0kndi95pg2qmjyhbcfbvopech9e6gwmzpmyngga></aex0kndi95pg2qmjyhbcfbvopech9e6gwmzpmyngga>
```

An this is the same for all templating tag.

How can I make this work?

**Comment by awmottaz** [comment]
Well, that is quite unexpected!

Off the top of my head, I don't know why that would happen. Could you please provide a full reproduction including your Prettier configuration and other relevant packages? A repository that I could clone and run myself to see reproduce issue would be ideal.

**Comment by jimblue** [comment]
Hey ! I've just try again and I don't have the pb anymore. I'm closing this issue. Will re-open it if needed.
