### ISSUE TITLE
how to use this plugin with vscode prettier extension?

### ISSUE THREAD

**Issue by coolRoger** [awmottaz/prettier-plugin-void-html#22]
Hi, i really need to use this plugin to pass w3c validation. I wanna know how to integrate this plugin with vscode prettier extension?

**Comment by awmottaz** [comment]
The extension mentions support for Prettier plugins in their docs: https://github.com/prettier/prettier-vscode/blob/main/README.md

If that's not working for you, take a look at #19 — you can skip the stuff about Vue configuration, but there are some steps there for setting up the VSCode extension. I haven't tried those steps myself, so YMMV.
