### ISSUE TITLE
Angular HTML Support

### ISSUE THREAD

**Issue by Coder-Zertrax** [awmottaz/prettier-plugin-void-html#23]
Hello @awmottaz,

first of all, thank you for your great HTML5 support plugin for prettier.

I work with angular and want to use your plugin for my Angular project and already added the support for Angular in your plugin on my local copy and work with it.
I would be happy if I could extend your plugin with a pullrequest.

Regards.

**Comment by awmottaz** [comment]
Thank you for your interest! Please read [the disclaimer in the README](https://github.com/awmottaz/prettier-plugin-void-html/blob/a32105c3716c6c11aa8f9f9d47af391c7ff4a4b3/README.md#languages). Supporting other languages is outside the scope of what I'm able to support with this plugin.

Other folks have had success extending this to support other languages, [such as Vue.js](https://github.com/awmottaz/prettier-plugin-void-html/issues/19). Maybe that can be useful to you as well.
